### ISSUE TITLE
Script fails if docker host isn't reachable

### ISSUE THREAD

**Issue by derek-adair** [joshuacox/mkpostgres#1]
Definitely a nit pick... but i'm on OSX and my docker host wasn't spun up, I did a `$ make temp` and got a big ol error... seems like this could be handled?

```
➜ make temp
cat: postgresqlcid: No such file or directory
docker: "kill" requires a minimum of 1 argument.
See 'docker kill --help'.

Usage:  docker kill [OPTIONS] CONTAINER [CONTAINER...]

Kill a running container
make: [kill] Error 1 (ignored)
cat: postgresqlcid: No such file or directory
docker: "rm" requires a minimum of 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
make: [rm-image] Error 1 (ignored)
rm: postgresqlcid: No such file or directory
make: [rm-image] Error 1 (ignored)
docker run \
    --cidfile="postgresqltemp" \
    --name `cat NAME`-postgresqltemp \
    -e POSTGRES_ROOT_PASSWORD=`cat POSTGRES_PASS` \
    -d \
    postgres:9
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
make: *** [postgresqltemp] Error 125

```

**Comment by joshuacox** [comment]
perhaps, how do you start your docker daemon?

**Comment by derek-adair** [comment]
docker-machine start default && eval "$(docker-machine env default)"

**Comment by joshuacox** [comment]
at the moment that is nothing even remotely how I do it on any of my machines, so I'm going to leave this one for the later bin

closing for now, I'm happy to reopen and discuss handling methods if you like (it would ammount to lots of IF statements relying on figuring out the OS and then docker installation methods, pretty much a mess)
