### ISSUE TITLE
make temp fails if image isn't pulled

### ISSUE THREAD

**Issue by derek-adair** [joshuacox/mkpostgres#2]
It should pull the image if its not there locally

**Comment by joshuacox** [comment]
should be fixed by https://github.com/joshuacox/mkpostgres/commit/ff09b0435f2b3043da4fffcfb3d5c17f6e06be7b

**Comment by joshuacox** [comment]
https://github.com/joshuacox/mkpostgres/commit/29885f6c9e2c8f57d9d40ed005f5c43f7e9591c2

fixes this issues somewhat, now you have to mind your own rm's (i.e. `make rmtemp` etc when you want to remove old containers)
