### ISSUE TITLE
Name container may be better as an optional config

### ISSUE THREAD

**Issue by derek-adair** [joshuacox/mkpostgres#7]
Not sure how much I care about the container names.  I like the way Compose handles this {foldername}_{service_name}.  For this I think it would be fine to just do the folder name.  It would look something like this.

my_app/
  Dockerfile.app <- my pthon image
  my_app_db/
    Dockerfile.db <- my db image

**Comment by joshuacox** [comment]
at this point this is how I link the containers is by name, it certainly could be based on directory, but for now I'll just let you modify the NAME file that gets left in the directory as you see fit
